name: wallet
description: "A wallet app for storing docs on device "
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  shared_preferences_android: ^2.4.10
  form_builder_image_picker: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

 
  assets:
    - assets/